# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveDebate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debox',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debox',
            name='name',
            field=models.CharField(default='some_string', max_length=50),
        ),
    ]
