# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveDebate', '0002_auto_20171128_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeBox',
        ),
    ]
